### ISSUE TITLE
Enter probe length dialog box

### ISSUE THREAD

**Issue by hannahblau** [TheJacksonLaboratory/VPV#101]
Enter Probe Length dialog box has the following sentence:

In some technologies, the probes are streptavidin-labeled magnetic beads are used to capture target sequences in solution; in other, variable length probes are attached to an array.

To make this correct English and more readable:

In some technologies, streptavidin-labeled magnetic beads are used to capture target sequences in solution; in others, variable length probes are attached to an array.

**Comment by pnrobinson** [comment]
Done!
