### ISSUE TITLE
Tail button of Show log window dysfunctional?

### ISSUE THREAD

**Issue by hannahblau** [TheJacksonLaboratory/VPV#102]
Not sure what this is supposed to do, but at the moment it appears to do nothing. I thought it might show just the last few lines of the log file (like the tail unix command) but I cannot see any changes after I click the button.

**Comment by pnrobinson** [comment]
It works for me. Are you sure that your log is long enough for there to be more than one page? Especially if you are just looking at a subset of terms, e.g., error? It is supposes to jump down to the last part of the file and show the entire "last page".

**Comment by hannahblau** [comment]
There's some unintentional interaction between the button that displays location in the log listing and the button that takes you to the tail of the log. If the location is displayed, then the tail button does not work. This is true whether or not timestamp is displayed simultaneously. But the tail button works if just the message or if timestamp + message are displayed.

If I click "show log" then "show location" then "tail", the tail button does not work. However, if I toggle the "show location" button to turn off location, the display immediately shifts to the last page of the log without any further clicks. As if the "tail" button was just waiting for the location to get turned off so it could do its thing.

**Comment by hannahblau** [comment]
When the tail button does work, it truncates the log so that you cannot go back to anything that occurred earlier than the first line on the last page of the log. In other words, the last page becomes the only page of the log. I find this weird, because I don't expect a tail command to change the contents of the file I'm looking at. And I think this will be inconvenient because something you see in the tail might make you want to go backwards in time to figure out what caused it, and now you cannot go back very far.

**Comment by pnrobinson** [comment]
The behavior was because the tail button was still pressed. I have added a style so that a user sees that this button is pressed or not, hopefully that is a sufficient clue that the button needs to be unpressed if you do not want to see just the tail.
