### ISSUE TITLE
Panel generation report does not say whether simple/extended approach

### ISSUE THREAD

**Issue by hannahblau** [TheJacksonLaboratory/VPV#103]
The Panel generation report (example attached) does not specify whether user chose the simple or the extended method of creating viewpoints --- should it? (Perhaps it would be obvious from the other parameters to someone who understands the biology.)
Also, the list of chosen restriction enzymes is not mentioned in the report, seems to me it should be.
[usabilityTest-report.txt](https://github.com/TheJacksonLaboratory/VPV/files/1484167/usabilityTest-report.txt)

**Comment by pnrobinson** [comment]
I amended the code to show this in the report and QC windows. 
I also added some documentation of this in the VPV read the docs website (please check this, see new issue #105).
