### ISSUE TITLE
Zoom In, Zoom Out buttons in Viewpoint window have surprising effects

### ISSUE THREAD

**Issue by hannahblau** [TheJacksonLaboratory/VPV#104]
Attached screenshots show the before/after of clicking zoom out/zoom in buttons on the viewpoint window of an analysis created with the simple method. The screenshots are from two different genes, PIGH and PIGL. I was surprised that zoom in/out selects fragments that were not previously selected. If this is the way they are supposed to work, then the effect should be documented. If this is not the way they are supposed to work, then the bug should be corrected.

PIGH before I do anything
![pighbefore](https://user-images.githubusercontent.com/8484992/32975280-d25c4116-cbd3-11e7-9e7c-c6058c479d24.png)

PIGH after I click on Zoom Out
![pighafterzoomout](https://user-images.githubusercontent.com/8484992/32975284-dd15a340-cbd3-11e7-9ca2-4f9f9266aa85.png)

then I click on Zoom In
![pighzoominafterzoomout](https://user-images.githubusercontent.com/8484992/32975298-e6a31fd2-cbd3-11e7-9409-420d848fa41b.png)

PIGL before I do anything
![piglbeforezoomin](https://user-images.githubusercontent.com/8484992/32975301-f19921c0-cbd3-11e7-9ec1-446f75d9d38b.png)

PIGL after I click on Zoom In
![piglafterzoomin](https://user-images.githubusercontent.com/8484992/32975306-fe88a522-cbd3-11e7-9b77-305ddf68f49b.png)

**Comment by hansenp** [comment]
Yes, this is the way it is supposed to work. For me it is also not that intuitive that zooming affects fragment selection, but we discussed it (#52) and decided to leave it as it is.

Documentation would be good.

**Comment by pnrobinson** [comment]
I have added this to the documentation. This behaviour seems the most logical to me, and it should be obvious to users what is happening because of the color codes as well.
