### ISSUE TITLE
Score display inconsistent

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/VPV#107]
The score that is shown in the analysis tab does not seem to match the score shown for the individual genes ("UCSC tab"). For instance, a SYK viewpoint had 66.95% on the analysis tab but only 8.59% on the UCSC tab.

**Comment by hansenp** [comment]
There are three different TSS for SYK.

<img width="1423" alt="screen shot 2017-12-01 at 4 35 53 pm" src="https://user-images.githubusercontent.com/10495485/33504523-bf8ee830-d6b5-11e7-8810-888d5e2790a0.png">

I checked them all. In all cases the same score was shown on the analysis and viewpoint tab. I guess you have mixed up the rows. Will close this issue.
