### ISSUE TITLE
URLMaker for hg38 and mm10

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#114]
In the class _URLMaker_ which is used to assemble the URLs for the embedded UCSC and the UCSC links I see only functions for hg19 and mm9. I wonder if there should also be functions for hg38 and mm10.

**Comment by pnrobinson** [comment]
yes..and also for rat and drosophila!

**Comment by pnrobinson** [comment]
Adding skeleton functions.
