### ISSUE TITLE
Set up and downstream size appropriately according to chosen enzyme(s)

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#115]
If an enzyme with low cutting frequency is chosen, e.g. HindIII , the current default of 1500 for the upstream size is too small. For many TSS the next cutting site is too far away. As a consequence, the containing fragment will not be in in the initial list of fragments and cannot be selected, no matter if it meets all criteria or not. See also issue #89.

Up and downstream sizes could be set depending on the chosen enzyme taking into account the average size of restriction fragments, which could either be hard coded or estimated by a simple formula. We have already discussed this.

**Comment by pnrobinson** [comment]
@hansenp 
I am thinking that it might be better to put this in the documentation and let the user decide about the parameters. Probably people who use this tool will have some degree of expertise or at least have read some papers, and we can write some recommended thresholds in the documentation. This is the sort of thing that if we have users who ask for the feature we could ask it?

**Comment by hansenp** [comment]
I added the following text to the readthedocs documention:
> Depending on which restriction enzyme is used the upstream and downstream size have to be set appropriately. The default values -5000 and +1500 are suitable for DpnII, but for enzymes that produce longer fragments such as HindIII larger values should be selected.
