### ISSUE TITLE
Set margin strategy default

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#120]
If I open a new project in VPV and generate viewpoints using the extended approach, I get only viewpoints withe fragments that have two valid margins, i.e. both margins fulfill the criteria for GC and repeat content.

This seems to be incorrect, because the default is to allow for single margins, and this option is also checked under _Design parameters -> Set margin strategy_.

**Comment by hansenp** [comment]
The selected option for _Set margin strategy_ should also be shown in the _VPV Parameter Check_ window.

**Comment by hansenp** [comment]
If select _require both margins_ and then right after _allow single margins_ the viewpoints are created as expected. It seems to work in principle, but on start up the default (_allow single margins_) is set and displayed incorrectly.

**Comment by hansenp** [comment]
I thin the problem is that the field in model is not set on start up. I added the last line to the following code:

```
        ToggleGroup marginToggleGroup = new ToggleGroup();
        marginToggleGroup.getToggles().addAll(singleMarginRadioMenuitem,bothMarginsRadioMenuitem);
        singleMarginRadioMenuitem.setOnAction(e -> {this.model.setAllowSingleMargin(true); e.consume();});
        bothMarginsRadioMenuitem.setOnAction(e -> {this.model.setAllowSingleMargin(false); e.consume();});
        singleMarginRadioMenuitem.setSelected(true);
        this.model.setAllowSingleMargin(true);
```
But this gives me a null pointer exception. How can I set this option in models on start up of VPV?

**Comment by pnrobinson** [comment]
Is it possible you are using an old serialized model? What happens if you save the model and then reopen? Mybe update the serialization ID of the class model?

**Comment by hansenp** [comment]
I always usined a fresh project. I think the problem that the setting of the option is only defined for _setOnAction_. As long as the option is not actively selected via the menu it stays unselected within model.

**Comment by hansenp** [comment]
I fixed the bug by setting the variable _allowSingleMargin_ in class _Model_ to _true_ by default. If this is not too ugly for you, please close this issue.

**Comment by pnrobinson** [comment]
The issue was in the function
 private void setInitializedValuesInGUI() 
this function sets the values in the GUI to values that are initialized from the Model. When we create viewpoints, the model was being set to the values in the GUI. I therefore added this
```
if (model.getAllowSingleMargin()) {
            this.bothMarginsRadioMenuitem.setSelected(false);
            this.singleMarginRadioMenuitem.setSelected(true);
        } else {
            this.bothMarginsRadioMenuitem.setSelected(true);
            this.singleMarginRadioMenuitem.setSelected(false);
        }
```
I have also changed to
```
 private boolean allowSingleMargin;
```
Please checn @hansenp

**Comment by hansenp** [comment]
It works now in as such that VPV now shows same as it does, i.e. by default _require both margins_ is checked and if I change nothing it will require both margins to be valid for fragment selection. If I change to _allow single margin_ it also works as expected.

However, I'm not sure if this is the intended behavior, because we originally we wanted to have _allow single margin_ as the default. And in _VPVMainPresenter_ we still have the line
`singleMarginRadioMenuitem.setSelected(true);`

**Comment by pnrobinson** [comment]
I have added a default value of true for setSingleMargin, and also updated the documentation.
