### ISSUE TITLE
Non-unique target regions if TSS of different genes are in close proximity

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#122]
If viewpoints for different genes overlap the exported target regions are not unique, i.e. the same target regions occur twice. Here an example for PDCD10 and SERPINI1:

![image](https://user-images.githubusercontent.com/10495485/33950624-2cb9f0f0-e02d-11e7-95e9-f2d3fa6c4d1d.png)

**Comment by pnrobinson** [comment]
Given the equals function in Segment, this "shouldn't" be happening...we need to figure this out!

**Comment by pnrobinson** [comment]
For output purposes, why do we need to keep track of genes? Please explain further.

**Comment by hansenp** [comment]
Agilents SureDesign wizard requires unique names for target regions in column four. Even though we cannot use the wizard, because it places probes outside target regions (we will submit the target regions to the design team of Agilent), I think it is good to have unique names for the target regions. But the names could also be e.g. consecutive numbers, not necessarily gene symbols. However, in my opinion gene symbols would be nicer, and this is not hard to implement. I will try it right now.

**Comment by hansenp** [comment]
Now we use an unique target region ID in combination with all associated gene symbols, e.g. the target region

`chr3	167455065	167455185	target_21:PDCD10,SERPINI1`

has the ID 21 and is associated with the genes PDCD10 and SERPINI1.

In UCSC the example from above looks now as follows:

<img width="1195" alt="screen shot 2017-12-14 at 9 39 48 am" src="https://user-images.githubusercontent.com/10495485/33997866-cdfcc880-e0b3-11e7-838b-0ef3e34c45ca.png">

I left the old code unchanged for the time being. If this solution is acceptable and no further bugs will occur, I will clean up the code and close this issue.

**Comment by pnrobinson** [comment]
@hansenp can we close this issue?

**Comment by hansenp** [comment]
Yes, I think so.
