### ISSUE TITLE
Test testMaxDistToGenomicPos fails

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#132]
If I try to build the package using:
`mvn package`
I get the following error messages:
```
[ERROR] Tests run: 5, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in vpvgui.model.viewpoint.SegmentFactoryTest
[ERROR] testVeryShortSegmentFactory(vpvgui.model.viewpoint.SegmentFactoryTest)  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.AssertionError
	at vpvgui.model.viewpoint.SegmentFactoryTest.testVeryShortSegmentFactory(SegmentFactoryTest.java:153)

[ERROR] testMaxDistToGenomicPos(vpvgui.model.viewpoint.SegmentFactoryTest)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: expected:<115> but was:<345>
	at vpvgui.model.viewpoint.SegmentFactoryTest.testMaxDistToGenomicPos(SegmentFactoryTest.java:102)


```

**Comment by hansenp** [comment]
I think I introduced the error here: https://github.com/TheJacksonLaboratory/VPV/commit/4bd2675a9dff1cc8345009ad08e1dce514b01ee6#diff-272cafa7f75cb7a5174caa01014e67a3

**Comment by hansenp** [comment]
The changes were related to issue #121.

**Comment by hansenp** [comment]
I changed the test function:
```
    @Test
    public void testMaxDistToGenomicPos() {
        Integer expected = maxDistToGenomicPosUp*3;
        Assert.assertEquals(expected, segmentFactory.getMaxDistToGenomicPosUp());
        expected = maxDistToGenomicPosDown*3;
        Assert.assertEquals(expected, segmentFactory.getMaxDistToGenomicPosDown());
    }
```
I multiplied the expected values by 3, because this was what I changed in the constructor to resolve #121:
```
+        maxDistToGenomicPosUp=maxDistToGenomicPosUp*3;
+        maxDistToGenomicPosDown=maxDistToGenomicPosDown*3;
```
Therefore, the expected values were wrong.

**Comment by hansenp** [comment]
The same problem occurs for the test `testVeryShortSegmentFactory`. The `SegmentFactory` object is initialized with `maxDistUp` (20), but inside the constructor this is multiplied by 3. Therefore, also the range in which cutting sites are expected have to be multiplied.
```
        for (Integer pos:gatcsites) {
            if (pos >= genomicPos - maxDistUp*3) {
                adjustedGatcSitesOffsetZero.add(pos);
            }
        }
```

**Comment by hansenp** [comment]
The package now be built with
`mvn package`
without test failures.

However, if I run all tests within IntelliJ, the test `testInitialization` in `ViewPointPresenterTest` fails.

**Comment by hansenp** [comment]
For `mvn package` this test is not performed.

The test function looks like this:
```
    /**
     * Test that the controller was properly initialized. E.g. that it contains model, ViewPoint, etc.
     *
     * @throws Exception
     */
    @Test
    public void testInitialization() throws Exception {
        Thread.sleep(4000); // just show the screen for now.
    }
```

**Comment by pnrobinson** [comment]
hmm it is unclear what is being tested here?

**Comment by hansenp** [comment]
The package can now be built with `mvn package`. The problem with the test `testInitialization` is probably due to an erroneous fxml file, which is not related to this issue. I created a separate issue #134.
