### ISSUE TITLE
Regulatory exome regions do not include fragments within viewpoints

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#138]
Regulatory exome regions do not include fragments within viewpoints. However, it would be good to know, if a differentially interacting fragment has a heterozygous variant.

There should be an additional category besides exons and regulatory regions.

**Comment by pnrobinson** [comment]
I have added this feature (develop and master should now be identical). @hansenp please check and if OK close issue.

**Comment by hansenp** [comment]
I cannot check this feature because the BED file cannot be loaded as custom track in UCSC.  UCSC's interface for uploading custom tracks reports:

<img width="931" alt="screen shot 2018-03-15 at 6 05 31 am" src="https://user-images.githubusercontent.com/10495485/37456940-ed855046-2816-11e8-8309-50b4bd866379.png">

This is due to spaces in the name field of _<OUT_PREFIX>-regulatoryExomePanel.bed_. This is line 2:

`chr1    8014852 8020999 ENSR00000000860[Promoter-flanking regions]`

If I remove the space from the name field, the error is reported for the next line that has a space within it's name field. Will try to fix this.

**Comment by hansenp** [comment]
It looks not bad. The viewpoint regions are included. However, not in one piece but each individual restriction fragment. Here an example:

<img width="1345" alt="screen shot 2018-03-15 at 6 37 57 am" src="https://user-images.githubusercontent.com/10495485/37458571-cc693f12-281b-11e8-8c2f-e8002af41971.png">

It would look more clearly, if the entire viewpoints were exported in one piece. Furthermore, there are gaps between the exported fragments.

<img width="1312" alt="screen shot 2018-03-15 at 6 44 50 am" src="https://user-images.githubusercontent.com/10495485/37458761-699561e4-281c-11e8-95b4-56b5302ffb13.png">

**Comment by pnrobinson** [comment]
Would it be better to include the viewpoint as one piece? I didnt think it would make much difference.

**Comment by hansenp** [comment]
It would not make much difference, but as it can be seen in the second screenshot there is also a bug. There are 1 bp gaps between the exported fragments. This might cause complications for probe design using the SureDesign wizard. Therefore, I fixed this by exporting the entire viewpoint. I changed the function:

```
    /** Add all viewpoints to our regulatory panel. The intention of this is that we would like to
     * enrich the DNA of all segments we are investigating in the capture HiC, in addition to the elements from the
     * Ensembl regulatory build. This will allow us to sequence things like variants in promotoers and UTRs.
     */
    private void collectViewPointsFromHiCPanel() {
        for (ViewPoint vp : this.model.getViewPointList()) {
            String name=String.format("viewpoint%s_%s:%d-%d",vp.getReferenceID(),vp.getReferenceID(),vp.getStartPos(),vp.getEndPos());
            RegulatoryBEDFileEntry VPentry = new RegulatoryBEDFileEntry(vp.getReferenceID(),vp.getStartPos(),vp.getEndPos(),name);
            this.regulatoryElementSet.add(VPentry);
        }
    }
```
