### ISSUE TITLE
Viewpoint tab - zoom out feature

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#52]
If I zoom out, only the table is updated, but not the range of the embedded UCSC screen. However, the colors of the fragments change. Even more worrying is the fact that zooming affects also the fragment selection.

**Example: Ace viewpoint (mm9, DpnII, CaptureC_gonad_gene_list_edit2_test.txt)**

After opening it looks as follows:

![image](https://user-images.githubusercontent.com/10495485/30474378-cacdeb5e-9a03-11e7-81cc-4b7e9cf69eb7.png)

After zooming in it looks as follows:

![image](https://user-images.githubusercontent.com/10495485/30474400-dc0c4e7e-9a03-11e7-8ab6-13089176cf8a.png)

**Comment by pnrobinson** [comment]
@hansenp I would say we should leave it in -- if there is a really important gene then a user may want to explore around it etc. I also do not think there is anything bad about having more fragments -- and there is probably no other reason for a user to zoom out. Zooming in will automatically deselect the fragments no longer in the viewpoint so it is easy to use. Is it enough if we explain this in read the docs?

**Comment by pnrobinson** [comment]
I have add this to the documentation, and think we can close this issue now.
