### ISSUE TITLE
Selection of tracks in embedded UCSC browser

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#61]
The selection of tracks is user specific. Either we show a minimal selection or we allow for user defined sections of tracks. In my opinion a minimal selection would be sufficient, because we already have the feature 'Copy UCSC link to clipboard'. A minimal selection should include RefSeq genes and repeats and GC content. I will ask Sala which other tracks might be of general interest.

**Comment by pnrobinson** [comment]
H3K27ac does not appear to be available for mm9 or mm10, but we do have RefSeq, RepeatMasker, and GC

**Comment by pnrobinson** [comment]
For human, we have the ENCODE track, which by default has

H3K27Ac Mark (Often Found Near Active Regulatory Elements) on 7 cell lines from ENCODE
DNaseI Hypersensitivity Clusters in 125 cell types from ENCODE (V3)
Transcription Factor ChIP-seq (161 factors) from ENCODE with Factorbook Motifs

I think we are pretty much as good as it will get, and if a user wants to see more, they can easily copy the link and work directly in the UCSC Browser to see other tracks.
Note I have also added gc5Base=full to get the GC content!

**Comment by hansenp** [comment]
Sounds good. In this case I would say less is more.
