### ISSUE TITLE
Score for viewpoints not always optimal

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#62]
Sala found some examples for which the viewpoint score seems to be not accurate. I will ask him to share some examples that can be used to improve the score.

**Comment by pnrobinson** [comment]
I tried two enzymes on the small set of human genes available from the help menu.
With DpnII, I got an average score of 43.5%. With NlaIII, I got an average score of 36.85%. Therefore, maybe it really does make a difference which enzyme you use. Let us discuss the score, and also discuss whether we should take the overall number of viewpoints with at least one active fragment into account (I think so). Then users can use the score to choose the best enzyme for their project.

**Comment by hansenp** [comment]
The score is associated to viewpoints. For a given viewpoint the score depends also on the enzyme, especially the cutting frequency. This is what I would expect. However, another question is, how the distribution of scores for many viewpoints differ, if two enzymes with the same cutting frequency
 are used.

The cutting frequency becomes even more important for the score, because we select also fragments that only partially overlap the interval between TSS-upstream size and TSS+downstream size.

Let's discuss this via Skype.

**Comment by hansenp** [comment]
I improved the score and good viewpoints, i.e. with many selected fragments predominantly near the TSS, show now up at the top of the list. This correlates well with the intuition.

I tried the new scores for the two enzymes DpnII and NlaIII and get the following average scores for all viewpoints:

DpnII: 41.81%
NlaIII: 44.12%

The score depends on the cutting frequency of the various enzymes in as such that short fragments won't be selected. In this regard, the higher the cutting frequency the lower the average score should be.

However, if I combine DpnII and NlaIII, I get an average score of 42.49%. This is not what I expected. This needs to be tested further.

**Comment by hansenp** [comment]
If I choose all 15 available enzymes, I get an average score of 36.69%. I would expect a much lower score.

It would be nice to know the average length of selected fragments. Maybe we can show them on the analysis pane.

**Comment by hansenp** [comment]
Assuming that the software including the score is valid, this could also mean that multiple enzymes can be used without too much loss of viewpoints or quality of viewpoints.

**Comment by pnrobinson** [comment]
@hansenp Where are we on this topic? Are we OK with the score? I think this is probably a less critical part of the entire program?

**Comment by hansenp** [comment]
I improved the score and now it correlates well with the intuition. Viewpoints with many selected fragments near the TSS show up at the top of the list.
