### ISSUE TITLE
Estimate number of probes

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#63]
Given the length of probes (default: 120), the total length of target regions and the tiling factor (default: 2), the expected total number of probes should be calculated and shown on top of the analysis tab. This would allow the user to assess the expected price category for probes.

**Comment by pnrobinson** [comment]
@hansenp Can we discuss the best relationship between the probe length and the margin size? Clearly the margin size needs to be at least as big as the probe length, correct? We do not currently check this. But how much bigger should the margin size be? Does it depend on the fragmentation that is being performed and on the read length?

**Comment by hansenp** [comment]
I think it only depends on the fragmentation step. I plotted the distribution of 5' ends around cutting sites only for unique valid pairs (HiCUP's name for mapped read pairs that are considered as valid interaction pairs):

![image](https://user-images.githubusercontent.com/10495485/32733172-ddf8ed28-c88e-11e7-99ab-e0a86d6257cd.png)

This was the motivation for choosing 250 bp as default marginSize. I agree that the marginSize should be at least one probe length.

**Comment by pnrobinson** [comment]
@hansenp Interesting figure. Why are the two distributions not symmetric?
SHouldn't we put a figure like this into the read the docs and then tell users that they need to adjust the fragmentation size to have a mode at around 250 and that the margin size should be the mode of the distribution of fragments that is to be expected for the experiment?

**Comment by hansenp** [comment]
I think they are not symmetric, because the short fragment sizes for DpnII. The distribution can be determined for all cutting sites inn the genome or only for fragments within target regions. What you see above is the ratio between those two. Only the inner parts of the two figures are within target regions.

The figures are preliminary. I was still looking for a good presentation. For HindIII it should look more symmetric.

Let's discuss this via Skype. This figure is important to motivate for the margin size of 250 bp for extended approach.

**Comment by hansenp** [comment]
We implemented the estimation of the number of the probes and tested it for different parameters by comparing it to the number of probes that were designed by Agilent's SureDesign wizard for the corresponding target regions. Therefore, I will close this issue.

I will create a new issue for the discussion about the dependency between of the average fragment length in the sequencing library and the margin size.
