### ISSUE TITLE
Facilitate the exchange of VPV projects between users

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#68]
So far a project can be saved and reopened on startup. The project '.ser' file is saved in a hidden directory in 'home'. The standard user doesn't know about hidden directories and won't find the '.ser' file.

It should also be possible to import and export a projects.

**Comment by hansenp** [comment]
The import/export procedure still does not work. If I

1. Export a project
2. Close VPV
3. Open VPV
4. Init a new project
5. Open the previously saved X.ser file

The analysis tab is still empty.

**Comment by hansenp** [comment]
In the current situation it would be quite useful to have the possibility to share projects, but it still does not work. Is there a quick solution for this? Otherwise, there is the workaround described above. If the exported _X.ser_ file is moved to the default location _/home/.vpvgui_, it works as expected.

**Comment by pnrobinson** [comment]
I have revised and tested this function and changed the name of the menu item to "Import project..."
