### ISSUE TITLE
Simple approach: TSS containing segment not active

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#72]
I found an example for the simple approach in which the TSS containing segment ist not active, even though it is long enough and there are no repeats. Do we also filter for GC content?

![image](https://user-images.githubusercontent.com/10495485/31676228-3ddfc320-b367-11e7-82d0-a1e459e79d4a.png)

**Comment by pnrobinson** [comment]
@ielis Is there a way of coding the cell with the invalid parameter red in these cases? For instance, if we have SIMPLE_APPROACH_MAX_GC=0.65 but some fragment actually has a GC content of 0.80 (80%), then the cell with 80% should be colored red (not the entire row)?

**Comment by pnrobinson** [comment]
I have added code to show the fragment in the table that overlaps the TSS with a (*). This helps a lot of understand the location of the fragments in the UCSC image. @hansenp I think then that this issue can be closed. We can leave the max frag size at 20,000 and write in the instructions that users can delete fragments bigger than their threshold value in the analysis table using the delete button. That would be the simplest thing for users and easy to implement (i.e., we do not need to do anything else).
