### ISSUE TITLE
VPV Parameter Check: Viewpoint (default) parameters not transferred

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#85]
If I leave the default paramters for Upstream size, Downstream size, etc., and click on 'Create Viewpoints', all paramters are shown as if set to zero in the Parameter Check window.

![image](https://user-images.githubusercontent.com/10495485/32437340-4b8468de-c2e7-11e7-9821-6962b2a48dea.png)

Only if new values are entered in the text fields, they are transferred to the Parameter Check window.

![image](https://user-images.githubusercontent.com/10495485/32437712-79acc6ce-c2e8-11e7-82c9-ef2fe339a0ac.png)

**Comment by pnrobinson** [comment]
The grey test is a prompt text that is just intended to show the kind of value that the user should enter. It does not act as a default value. Therefore, this is the current intended behavior.
If we want to provide default values, then we could add code that would substitute these values if the user does not enter anything.
If we want to do this, then we need to decide on the best default values?

**Comment by hansenp** [comment]
I think 5000 and 1500 for up and downstream size are quite usual. Also 120 bp for the minimum fragment size is plausible.

More challenging are the parameters for the GC and repetitive content. I suggest a systematic analysis of the probes generated by the SureDesign wizard.

The easiest and most beautiful would be if we had the code of the SureDesign probe selection algorithm. Then we could simply include this step into VPV.

**Comment by pnrobinson** [comment]
I have implemented it such that if the user does not enter anything then the default values are taken for the analysis. Still the default values are shown in gray in the GUI, hopefully a nice effect.
