### ISSUE TITLE
Simple approach: Fragment with 100% repetitive content selected

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#87]
If I run VPV only on the gene _C6orf99_ using the following parameters in _Simple_ mode:

![image](https://user-images.githubusercontent.com/10495485/32447287-ecc32bda-c30b-11e7-94fe-508b62fb6277.png)

I get a viewpoint with one selected fragment. This fragments covers the TSS and both magins are 100% repetitive.

![image](https://user-images.githubusercontent.com/10495485/32447401-483e2d20-c30c-11e7-9bf6-bc71fb27c202.png)

**Comment by hansenp** [comment]
For the _Extended_ mode, the same fragment is not selected.

**Comment by hansenp** [comment]
I added a variable _SIMPLE_APPROACH_MAX_REPEAT_ to the class ViewPoint. For the simple approach this parameter is hard coded, analogous to those for GC content.
```

    /** Minimum allowable GC content for simple approach */
    private static final double SIMPLE_APPROACH_MIN_GC=0.25;
    /** Maximum allowable GC content for simple approach */
    private static final double SIMPLE_APPROACH_MAX_GC=0.65;
    /** Maximum allowable repetitive content for simple approach */
    private static final double SIMPLE_APPROACH_MAX_REPEAT=0.30;
```
Then I added a corresponding condition to the function _generateViewpointSimple_

```
            if (gc >= SIMPLE_APPROACH_MIN_GC
                    && gc <= SIMPLE_APPROACH_MAX_GC
                    && length >= SIMPLE_APPROACH_MINSIZE
                    && length <= SIMPLE_APPROACH_MAXSIZE
                    && repeatUp <= SIMPLE_APPROACH_MAX_REPEAT) {
```
After this modification the repetitive fragment is not selected anymore.

However, why do we not use the same parameters as for as for the _Extended_ approach from the _Set up_ tab?

**Comment by pnrobinson** [comment]
Should this be different from the other repeat threshold? Do we need to have separate variables (this might have been my code, I admit)? Or can we use the same 3 variables for extended and simple?

**Comment by pnrobinson** [comment]
I do not understand how the margin size is used in the simple approach -- should it be different from the extended approach? I agree we can use the same variables, but let us think about the proper way to treat the margeinSize

**Comment by hansenp** [comment]
The margin size is the length of the regions at the ends of restriction fragments that are exported as target regions (blue). These target regions are subsequently used as input for Agilent's SureDesign wizard in order to get the probes (red).

![image](https://user-images.githubusercontent.com/10495485/32598349-e2d9ff92-c539-11e7-849f-7df18cbea3fd.png)

For the simple approach we would like to have that the target regions (blue) equal the probe regions (red).

![image](https://user-images.githubusercontent.com/10495485/32598675-a52299ce-c53a-11e7-863e-031b1d334b07.png)

To achieve this we could set _marginSize = probeLength_ for the simple approach.

**Comment by pnrobinson** [comment]
I made the following change, OK?
Note that previously we did not check for repeatDown, I added this too
```
// originating from the centralized fragment containing 'genomicPos' (included) openExistingProject fragment-wise in UPSTREAM direction
            double gc = centerSegment.getGCcontent();
            double repeatUp = centerSegment.getRepeatContentMarginUp();
            double repeatDown = centerSegment.getRepeatContentMarginDown();
            int length = centerSegment.length();
            if (gc >= minGcContent
                    && gc <= maxGcContent
                    && length >= SIMPLE_APPROACH_MINSIZE
                    && length <= SIMPLE_APPROACH_MAXSIZE
                    && repeatUp <= maximumRepeatContent
                    && repeatDown <= maximumRepeatContent) {
```

**Comment by pnrobinson** [comment]
After conversation today I am changing SIMPLE_APPROACH_MINSIZE to this.minFragSize
We need to figure out what to do with  SIMPLE_APPROACH_MAXSIZE. I would suggest we just set it to Justin's default value. It will not matter much, at worst a few probes will be ordered that are too big but this can be filtered out in the analysis stage.

**Comment by hansenp** [comment]
Seems to be done.
