### ISSUE TITLE
Design parameters: margin size

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/VPV#88]
If I open the window for the setting of the margin size, there is stated that the margin size is used for calculating the repeat content. But the margin size is essential part of the extended approach. It defines the size of regions at the ends of restriction fragment that are exported as target regions.

**Comment by pnrobinson** [comment]
@hansenp I have made new dialogs that show some explanation for the parameters. Please let me know if the explanations are good (close the issue if OK).

**Comment by hansenp** [comment]
The help dialogs are very useful. Currently, there is no explanation of _marginSize_. I would like to add it. Where can I find the corresponding files?

**Comment by pnrobinson** [comment]
This is in the class
https://github.com/TheJacksonLaboratory/VPV/blob/master/src/main/java/vpvgui/gui/popupdialog/PopupFactory.java

**Comment by hansenp** [comment]
Extended the description as follows:

![image](https://user-images.githubusercontent.com/10495485/32739908-873c2df2-c8a1-11e7-9174-b20a4d65033c.png)

Will close this issue.
