### ISSUE TITLE
genemap2

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/VPV#90]
Can we use just genemap2 in RefGeneParser? (just one of genemap2 or genemap, probably with a few adjustments)?

**Comment by hansenp** [comment]
I introduced _genemap_2_ (see #59, #60), because TSS on different chromosomes are possible for a given gene. I left _genemap_ untouched to avoid for me unpredictable side effects.

**Comment by pnrobinson** [comment]
I changed genemap_2 slightly
 //String key = name2.concat(chrom);
 String key=String.format("%s_%s_%d",name2,chrom,gPos);

this produces keys like
AJM1_chr9_139736958
CSKMT_chr11_62432779
CAVIN4_chr9_103340361
APOC3_chr11_116700608

**Comment by pnrobinson** [comment]
This will work even in cases where a gene has multiple copies on one chromosome. 
I also renamed the original genemap to geneSymbolMap and genemap_2 to gene2chromosomePosMap
I think we need both maps to do the parsing correctly. I think the issue is now closed, but note there may be different results if one gene had multiple copies on one chromosome. This should not be an issue for the vast majority of protein coding genes we are interested in anyway.

**Comment by hansenp** [comment]
> I think the issue is now closed, but note there may be different results if one gene had multiple copies on one chromosome. This should not be an issue for the vast majority of protein coding genes we are interested in anyway.

I'm not sure, if I understand correctly. This happens quite often. I will check this tomorrow.

**Comment by hansenp** [comment]
Checked it for IL9R and RNUN6-2. Everything seems to work as before.

![image](https://user-images.githubusercontent.com/10495485/32831504-d2bc11a4-c9f8-11e7-97ca-b4e1b4635af0.png)
