### ISSUE TITLE
cannot build package in IntelliJ: test failures

### ISSUE THREAD

**Issue by hannahblau** [TheJacksonLaboratory/VPV#93]
See attached file for contents of the console when I attempt to rebuild the VPV package within IntelliJ. It fails due to two tests.
[buildErrors.txt](https://github.com/TheJacksonLaboratory/VPV/files/1476446/buildErrors.txt)

**Comment by pnrobinson** [comment]
[ERROR] testTotalNumberOfGenes(vpvgui.io.RefGeneParserTest)  Time elapsed: 0.016 s  <<< FAILURE!
java.lang.AssertionError: expected:<19> but was:<22>
	at vpvgui.io.RefGeneParserTest.testTotalNumberOfGenes(RefGeneParserTest.java:54)

and

testCreateUCSChg38(vpvgui.model.DataSourceTest)  Time elapsed: 0.002 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...enPath/hg38/bigZips/[]chromFa.tar.gz> but was:<...enPath/hg38/bigZips/[hg38.]chromFa.tar.gz>
	at vpvgui.model.DataSourceTest.testCreateUCSChg38(DataSourceTest.java:54)

**Comment by pnrobinson** [comment]
The correct answer to this test should be 19 genes
```
$ zcat refGeneSmall.txt.gz | cut -f 13 | sort | uniq | wc -l 
19
```

**Comment by pnrobinson** [comment]
The issue with the first bug was that  public int n_totalRefGenes() was returning the size of the gene2chromosomalPositionMap (this map has one item for each transcription start site, and thus can be and was larger than the actual number of genes). I changed this to 
```
 return this.geneSymbolMap.size();
```
and the test is passed again. This was related to the refatoring with genemap_2 etc.

**Comment by pnrobinson** [comment]
The second bug is related to the fact that UCSC has changed the URL for downloading the hg38 genome file. I have updated the test class.
